spring:
#  #静态资源处理
#  resources:
#    #启用默认静态资源处理，默认启用
#    add-mappingsz: true
#    cache:
#      cachecontrol:
#        #缓存响应时间
#        max-age: 3600
#    chain:
#      #资源链中启用缓存，默认启用
#      cache: true
#      #启用资源链，默认禁用
#      enabled: true
#      compressed: true
#      html-application-cache: true
#    static-locations: classpath:/static/

  #thymeleaf 配置
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      #连接池名
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 360000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  #RabbitMQ配置
  spring:
    #RabbitMQ
    rabbitmq:
      #服务器地址
      host: 192.168.0.16 #用户名
      username: guest #密码
      password: guest #虚拟主机 virtual-host: / #端口
      port: 5672
      listener:
        simple:
          #消费者最小数量
          concurrency: 10
          #消费者最大数量
          max-concurrency: 10 #限制消费者每次只处理一条消息，处理完再继续下一条消息 prefetch: 1
          #启动时是否默认启动容器，默认true
          auto-startup: true
          #被拒绝时重新进入队列
          default-requeue-rejected: true
      template:
        retry:
          #发布重试，默认false
          enabled: true
          #重试时间 默认1000ms
          initial-interval: 1000
          #重试最大次数，默认3次
          max-attempts: 3
          #重试最大间隔时间，默认10000ms
          max-interval: 10000
          #重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s multiplier: 1.0
          multiplier: 1.0


  #redis配置
  redis:

    #服务器地址
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms

    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 0




mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名（默认是类名）
  type-aliases-package: com.xxxx.seckil.pojo


#Mybatis SQL打印（方法接口是在的包，不是mapper.xml所在的包）
logging:
  level:
    com.xxxx.seckil.mapper: debug


##########